In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('raw_data.csv')

In [17]:
df.head()

,Date,Open,High,Low,Close,Adj.Close,Volume,revenue,gross_profit,net_income,...,VWAP_bid_volume_percentage,VWAP_ask_volume_percentage,px_ask,px_bid,px_mid,px_volume,total_analyst_recommendation,turn_over,egy_rec,symbol
0,1/10/2013,12.320000,12.380000,12.160000,12.230000,11.405354,12659200,9.248770e+08,4.633640e+08,6.043700e+07,...,43.6750,56.3250,12.23,12.22,12.225,12659713,34,1.549487e+08,3.529,NVDA
1,1/10/2013,105.459999,111.500000,105.400002,110.570000,110.570000,9880100,6.335346e+09,4.342033e+09,2.795482e+09,...,52.8000,52.8000,110.58,110.55,110.565,9885362,30,1.078537e+09,4.200,BIDU
2,1/10/2013,34.560001,34.919998,34.410000,34.910000,32.459404,17843600,8.181000e+09,6.406000e+09,2.034000e+09,...,46.0631,53.9369,34.91,34.90,34.905,17843884,43,6.193052e+08,4.326,ORCL
3,1/10/2013,20.350000,20.490000,20.290001,20.440001,17.269114,31419200,1.187600e+10,7.239000e+09,2.092000e+09,...,51.6469,48.3531,20.45,20.44,20.445,31419269,46,6.414561e+08,4.174,CSCO
4,1/10/2013,7.370000,7.440000,7.280000,7.420000,7.420000,18685600,1.834000e+09,2.170000e+08,-2.750000e+08,...,42.9326,57.0674,7.42,7.41,7.415,18692802,28,1.376464e+08,4.536,MU

In [4]:
del df['Unnamed: 0']

In [5]:
df.head()

,Date,Open,High,Low,Close,Adj.Close,Volume,revenue,gross_profit,net_income,...,VWAP_bid_volume_percentage,VWAP_ask_volume_percentage,px_ask,px_bid,px_mid,px_volume,total_analyst_recommendation,turn_over,egy_rec,symbol
0,1/2/2013,79.117142,79.285713,77.375717,78.432854,56.532833,140129500,5.451200e+10,2.106000e+10,1.307800e+10,...,43.4942,56.5058,78.3871,78.3864,78.3864,140124866,61,1.098056e+10,4.639,AAPL
1,1/3/2013,78.268570,78.524284,77.285713,77.442856,55.819256,88241300,5.451200e+10,2.106000e+10,1.307800e+10,...,45.8240,54.1760,77.4914,77.4793,77.4793,88240950,61,6.879276e+09,4.639,AAPL
2,1/4/2013,76.709999,76.947144,75.118568,75.285713,54.264439,148583400,5.451200e+10,2.106000e+10,1.307800e+10,...,52.3691,47.6309,75.2871,75.2729,75.2729,148581860,60,1.126494e+10,4.633,AAPL
3,1/7/2013,74.571426,75.614288,73.599998,74.842857,53.945240,121039100,5.451200e+10,2.106000e+10,1.307800e+10,...,48.8563,51.1437,74.8843,74.8686,74.8686,121038176,60,9.029261e+09,4.633,AAPL
4,1/8/2013,75.601425,75.984283,74.464287,75.044289,54.090424,114676800,5.451200e+10,2.106000e+10,1.307800e+10,...,49.4913,50.5088,75.0571,75.0400,75.0400,114676751,60,8.612151e+09,4.633,AAPL

In [6]:
df = df.sort_values(by='Date', ascending=True)

In [7]:
df.head()

,Date,Open,High,Low,Close,Adj.Close,Volume,revenue,gross_profit,net_income,...,VWAP_bid_volume_percentage,VWAP_ask_volume_percentage,px_ask,px_bid,px_mid,px_volume,total_analyst_recommendation,turn_over,egy_rec,symbol
13206,1/10/2013,12.320000,12.380000,12.160000,12.230000,11.405354,12659200,9.248770e+08,4.633640e+08,6.043700e+07,...,43.6750,56.3250,12.23,12.22,12.225,12659713,34,1.549487e+08,3.529,NVDA
3966,1/10/2013,105.459999,111.500000,105.400002,110.570000,110.570000,9880100,6.335346e+09,4.342033e+09,2.795482e+09,...,52.8000,52.8000,110.58,110.55,110.565,9885362,30,1.078537e+09,4.200,BIDU
14526,1/10/2013,34.560001,34.919998,34.410000,34.910000,32.459404,17843600,8.181000e+09,6.406000e+09,2.034000e+09,...,46.0631,53.9369,34.91,34.90,34.905,17843884,43,6.193052e+08,4.326,ORCL
6606,1/10/2013,20.350000,20.490000,20.290001,20.440001,17.269114,31419200,1.187600e+10,7.239000e+09,2.092000e+09,...,51.6469,48.3531,20.45,20.44,20.445,31419269,46,6.414561e+08,4.174,CSCO
11886,1/10/2013,7.370000,7.440000,7.280000,7.420000,7.420000,18685600,1.834000e+09,2.170000e+08,-2.750000e+08,...,42.9326,57.0674,7.42,7.41,7.415,18692802,28,1.376464e+08,4.536,MU

In [8]:
df.to_csv('raw_data.csv',index=False)

In [13]:
df = pd.read_csv('raw_data.csv')

In [14]:
df.head(20)

,Date,Open,High,Low,Close,Adj.Close,Volume,revenue,gross_profit,net_income,...,VWAP_bid_volume_percentage,VWAP_ask_volume_percentage,px_ask,px_bid,px_mid,px_volume,total_analyst_recommendation,turn_over,egy_rec,symbol
0,1/10/2013,12.320000,12.380000,12.160000,12.230000,11.405354,12659200,9.248770e+08,4.633640e+08,6.043700e+07,...,43.6750,56.3250,12.2300,12.2200,12.2250,12659713,34,1.549487e+08,3.529,NVDA
1,1/10/2013,105.459999,111.500000,105.400002,110.570000,110.570000,9880100,6.335346e+09,4.342033e+09,2.795482e+09,...,52.8000,52.8000,110.5800,110.5500,110.5650,9885362,30,1.078537e+09,4.200,BIDU
2,1/10/2013,34.560001,34.919998,34.410000,34.910000,32.459404,17843600,8.181000e+09,6.406000e+09,2.034000e+09,...,46.0631,53.9369,34.9100,34.9000,34.9050,17843884,43,6.193052e+08,4.326,ORCL
3,1/10/2013,20.350000,20.490000,20.290001,20.440001,17.269114,31419200,1.187600e+10,7.239000e+09,2.092000e+09,...,51.6469,48.3531,20.4500,20.4400,20.4450,31419269,46,6.414561e+08,4.174,CSCO
4,1/10/2013,7.370000,7.440000,7.280000,7.420000,7.420000,18685600,1.834000e+09,2.170000e+08,-2.750000e+08,...,42.9326,57.0674,7.4200,7.4100,7.4150,18692802,28,1.376464e+08,4.536,MU
5,1/10/2013,38.750000,38.779999,38.090000,38.619999,38.619999,3645200,1.007873e+09,8.511890e+08,6.511700e+07,...,55.9223,44.0778,38.6200,38.6100,38.6150,3645200,25,1.404139e+08,3.680,ADBE
6,1/10/2013,32.110001,32.570000,32.080002,32.430000,28.241238,8018700,2.979000e+09,1.445000e+09,2.640000e+08,...,46.7051,53.2949,32.4400,32.4300,32.4350,8019233,8019233,2.596788e+08,3.357,TXN
7,1/10/2013,26.650000,26.980000,26.290001,26.459999,23.060240,71431300,1.600800e+10,1.184000e+10,4.466000e+09,...,53.3731,46.6269,26.4800,26.4750,26.4750,71430810,44,1.893123e+09,4.227,MSFT
8,1/10/2013,43.150002,43.457500,42.457500,43.279999,43.279999,4749200,6.954670e+08,5.439160e+08,-1.947500e+07,...,53.4394,46.5606,43.2625,43.2675,43.2675,4751260,40,2.040562e+08,4.500,CRM
9,1/10/2013,75.507141,75.531425,73.645714,74.787140,53.905075,150286500,5.451200e+10,2.106000e+10,1.307800e+10,...,48.8746,51.1254,74.8029,74.7914,74.7914,150285296,60,1.118410e+10,4.633,AAPL
10,1/10/2013,21.610001,21.820000,21.530001,21.799999,18.445814,44621600,1.258000e+10,7.066000e+09,2.045000e+09,...,51.1518,48.8483,21.8200,21.8100,21.8150,44629665,51,9.686980e+08,3.431,INTC
11,1/10/2013,65.470001,65.529999,64.389999,64.779999,55.555172,13114000,6.018000e+09,3.781000e+09,1.903000e+09,...,49.7491,50.2509,64.7600,64.7500,64.7550,13113968,48,8.488287e+08,4.667,QCOM
12,1/10/2013,371.786774,372.872864,367.117126,371.111115,371.111115,3667700,1.441900e+10,8.206000e+09,2.886000e+09,...,53.2863,46.7137,371.0940,371.0390,371.0670,1835780,42,1.356515e+09,4.524,GOOGL
13,1/10/2013,192.649994,192.960007,191.279999,192.880005,164.264450,3608100,2.930400e+10,1.067800e+10,3.032000e+09,...,46.9168,53.0832,192.8400,192.8500,192.8450,3608049,31,6.938150e+08,3.903,IBM
14,1/10/2014,74.110001,74.500000,73.169998,73.870003,64.581253,8877600,6.622000e+09,3.916000e+09,1.874000e+09,...,54.3790,45.6210,73.8800,73.8700,73.8750,8877926,45,6.548076e+08,4.467,QCOM
15,1/10/2014,570.110107,570.110107,561.686707,565.655640,565.655640,4282700,1.441900e+10,8.206000e+09,2.886000e+09,...,47.8185,52.1815,565.6380,565.5070,565.5730,2145560,45,2.419414e+09,4.378,GOOGL
16,1/10/2014,35.900002,36.150002,35.750000,36.040001,32.359745,40548800,1.852900e+10,1.338400e+10,5.244000e+09,...,50.6108,49.3892,36.0500,36.0450,36.0450,40558766,39,1.457985e+09,3.641,MSFT
17,1/10/2014,43.150002,43.250000,42.740002,43.110001,38.634369,5330900,3.028000e+09,1.640000e+09,5.110000e+08,...,54.2686,45.7314,43.1200,43.1100,43.1150,5330933,5330933,2.289178e+08,3.225,TXN
18,1/10/2014,77.118568,77.257141,75.872856,76.134285,65.502510,76244000,5.759400e+10,2.184600e+10,1.307200e+10,...,46.7826,53.2174,76.1314,76.1271,76.1271,76320664,59,5.820255e+09,4.390,AAPL
19,1/10/2014,22.230000,22.280001,21.990000,22.219999,19.343740,30318600,1.208500e+10,7.407000e+09,1.996000e+09,...,45.1122,54.8878,22.2300,22.2200,22.2250,30321787,45,6.717070e+08,3.933,CSCO