In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('raw_data.csv')

/Users/mani/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
df.head()

,Unnamed: 0,Date,Open,High,Low,Close,Adj.Close,Volume,revenue,gross_profit,...,MFI,Volat,CMO.Ad,CMO.Vo,RunMean,RunSD,GMMA,KST,DPO,DVI
0,357,1/16/2014,171.300003,174.570007,169.750000,173.000000,173.000000,2975000,9.522913e+09,5.866424e+09,...,42.611467,0.195193,5.660541,-36.456573,133.189018,190.302970,1.332843e+07,-315.754725,-11480300,0.596032
1,358,1/16/2014,74.470001,74.879997,74.010002,74.720001,65.324356,10263200,6.622000e+09,3.916000e+09,...,39.304866,0.194706,-2.040986,2.451821,104.865723,173.466198,1.179582e+07,-294.546266,-8751740,0.768254
2,359,1/16/2014,187.529999,188.990005,186.800003,188.759995,163.875153,4770300,2.738500e+10,1.062700e+10,...,45.818767,0.192173,6.384432,-13.435674,121.638723,172.565988,8.283059e+06,-246.890280,-9011560,0.613492
3,360,1/16/2014,22.850000,22.910000,22.629999,22.780001,19.831251,38918100,1.208500e+10,7.407000e+09,...,40.648559,0.182808,-0.972015,7.983797,123.149723,171.520173,2.360058e+07,-191.905480,25906940,0.378571
4,361,1/16/2014,61.590000,61.980000,61.259998,61.630001,61.630001,3747800,1.000120e+09,8.516110e+08,...,43.238445,0.175726,1.249604,-4.414016,125.623723,170.311890,1.367419e+07,-113.246354,-9203390,0.365079

In [7]:
symbol = df.symbol

In [11]:
del df['Unnamed: 0']

In [12]:
del df['symbol']

In [13]:
df.insert(0, 'symbol',symbol)

In [14]:
df.head()

,symbol,Date,Open,High,Low,Close,Adj.Close,Volume,revenue,gross_profit,...,MFI,Volat,CMO.Ad,CMO.Vo,RunMean,RunSD,GMMA,KST,DPO,DVI
0,BIDU,1/16/2014,171.300003,174.570007,169.750000,173.000000,173.000000,2975000,9.522913e+09,5.866424e+09,...,42.611467,0.195193,5.660541,-36.456573,133.189018,190.302970,1.332843e+07,-315.754725,-11480300,0.596032
1,QCOM,1/16/2014,74.470001,74.879997,74.010002,74.720001,65.324356,10263200,6.622000e+09,3.916000e+09,...,39.304866,0.194706,-2.040986,2.451821,104.865723,173.466198,1.179582e+07,-294.546266,-8751740,0.768254
2,IBM,1/16/2014,187.529999,188.990005,186.800003,188.759995,163.875153,4770300,2.738500e+10,1.062700e+10,...,45.818767,0.192173,6.384432,-13.435674,121.638723,172.565988,8.283059e+06,-246.890280,-9011560,0.613492
3,CSCO,1/16/2014,22.850000,22.910000,22.629999,22.780001,19.831251,38918100,1.208500e+10,7.407000e+09,...,40.648559,0.182808,-0.972015,7.983797,123.149723,171.520173,2.360058e+07,-191.905480,25906940,0.378571
4,ADBE,1/16/2014,61.590000,61.980000,61.259998,61.630001,61.630001,3747800,1.000120e+09,8.516110e+08,...,43.238445,0.175726,1.249604,-4.414016,125.623723,170.311890,1.367419e+07,-113.246354,-9203390,0.365079

In [23]:
df.Date=  pd.to_datetime(df.Date)

In [24]:
df.to_csv('raw_data.csv',index=False)

In [25]:
df.head()

,symbol,Date,Open,High,Low,Close,Adj.Close,Volume,revenue,gross_profit,...,MFI,Volat,CMO.Ad,CMO.Vo,RunMean,RunSD,GMMA,KST,DPO,DVI
0,BIDU,2014-01-16,171.300003,174.570007,169.750000,173.000000,173.000000,2975000,9.522913e+09,5.866424e+09,...,42.611467,0.195193,5.660541,-36.456573,133.189018,190.302970,1.332843e+07,-315.754725,-11480300,0.596032
1,QCOM,2014-01-16,74.470001,74.879997,74.010002,74.720001,65.324356,10263200,6.622000e+09,3.916000e+09,...,39.304866,0.194706,-2.040986,2.451821,104.865723,173.466198,1.179582e+07,-294.546266,-8751740,0.768254
2,IBM,2014-01-16,187.529999,188.990005,186.800003,188.759995,163.875153,4770300,2.738500e+10,1.062700e+10,...,45.818767,0.192173,6.384432,-13.435674,121.638723,172.565988,8.283059e+06,-246.890280,-9011560,0.613492
3,CSCO,2014-01-16,22.850000,22.910000,22.629999,22.780001,19.831251,38918100,1.208500e+10,7.407000e+09,...,40.648559,0.182808,-0.972015,7.983797,123.149723,171.520173,2.360058e+07,-191.905480,25906940,0.378571
4,ADBE,2014-01-16,61.590000,61.980000,61.259998,61.630001,61.630001,3747800,1.000120e+09,8.516110e+08,...,43.238445,0.175726,1.249604,-4.414016,125.623723,170.311890,1.367419e+07,-113.246354,-9203390,0.365079